crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from django.urls import include, path
from common.views import handler404, handler500

app_name = 'crm'

urlpatterns = [
    path('', include('common.urls', namespace="common")),
    path('', include('django.contrib.auth.urls')),
    path('marketing/', include('marketing.urls', namespace="marketing")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('leads/', include('leads.urls', namespace="leads")),
    path('contacts/', include('contacts.urls', namespace="contacts")),
    path('opportunities/',
         include('opportunity.urls', namespace="opportunities")),
    path('cases/', include('cases.urls', namespace="cases")),
    path('tasks/', include('tasks.urls', namespace="tasks")),
    path('invoices/', include('invoices.urls', namespace="invoices")),
    path('events/', include('events.urls', namespace="events")),
    path('teams/', include('teams.urls', namespace="teams")),
    path('emails/', include('emails.urls', namespace="emails")),
    # path('planner/', include('planner.urls', namespace="planner")),
    path('logout/', views.LogoutView, {'next_page': '/login/'}, name="logout"),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = handler404
handler500 = handler500

marketing/urls.py
from django.urls import path, include
from .views import (
    dashboard, contact_lists, contacts_list, contact_list_new, contact_list_detail, edit_contact,
    email_template_list, email_template_new, email_template_edit, email_template_delete,
    email_template_detail, campaign_list, campaign_new, campaign_details, campaign_delete,
    edit_contact_list, failed_contact_list_download_delete,
    campaign_link_click, campaign_open, demo_file_download, delete_contact, unsubscribe_from_campaign, contact_detail,
    download_contacts_for_campaign, create_campaign_from_template,
    download_links_clicked, delete_multiple_contacts, download_failed_contacts, delete_all_contacts,
    add_email_for_campaigns, list_all_emails_for_campaigns, edit_email_for_campaigns, delete_email_for_campaigns,
    add_blocked_domain, blocked_domain_list, edit_blocked_domain, delete_blocked_domain,
    add_blocked_email, blocked_email_list, edit_blocked_email, delete_blocked_email,
    contacts_list_elastic_search,
    # MarketingContactEmailSearch,
    # contacts_list_new
    # delete_contact_list
    # campaign_edit
    # edit_failed_contact
    # delete_failed_contact
    # failed_contact_list_detail
)

app_name = 'marketing'

urlpatterns = [
    path('', dashboard, name='dashboard'),

    path('contact-list/', contact_lists, name='contact_lists'),
    path('contacts/<int:pk>/edit/', edit_contact, name='edit_contact'),
    path('contacts/<int:pk>/delete/', delete_contact, name='delete_contact'),
    path('contacts/', contacts_list_elastic_search, name='contacts_list'),
    path('contact-list/create/', contact_list_new, name='contact_list_new'),
    # path('cl/list/cnew/', contacts_list_new, name='contacts_list_new'),
    path('contact-list/<int:pk>/detail/', contact_list_detail, name='contact_list_detail'),
    # path('contact-list/<int:pk>/failed/', failed_contact_list_detail, name='failed_contact_list_detail'),
    # path('contact-list/<int:pk>/failed/edit/', edit_failed_contact, name='edit_failed_contact'),
    # path('contact-list/<int:pk>/failed/delete/', delete_failed_contact, name='delete_failed_contact'),
    path('contact-list/<int:pk>/failed/download/',
         failed_contact_list_download_delete, name='failed_contact_list_download_delete'),
    path('contact-list/<int:pk>/edit/', edit_contact_list, name='edit_contact_list'),
    # path('cl/list/<int:pk>/delete/', delete_contact_list, name='delete_contact_list'),

    path('email-templates/', email_template_list, name='email_template_list'),
    path('email-templates/create/', email_template_new, name='email_template_new'),
    path('email-templates/<int:pk>/edit/', email_template_edit, name='email_template_edit'),
    path('email-templates/<int:pk>/detail/', email_template_detail, name='email_template_detail'),
    path('email-templates/<int:pk>/delete/', email_template_delete, name='email_template_delete'),

    path('campaigns/', campaign_list, name='campaign_list'),
    path('campaigns/create/', campaign_new, name='campaign_new'),
    # path('cm/<int:pk>/edit/', campaign_edit, name='campaign_edit'),
    path('campaigns/<int:pk>/details/', campaign_details, name='campaign_details'),
    path('campaigns/<int:pk>/delete/', campaign_delete, name='campaign_delete'),
    path('cm/link/<int:link_id>/e/<int:email_id>/', campaign_link_click, name='campaign_link_click'),
    path('cm/track-email/<int:campaign_log_id>/contact/<int:email_id>/', campaign_open, name='campaign_open'),
    path('demo-file-download-for-contacts-list/', demo_file_download, name='demo_file_download'),
    path('unsubscribe-from-campaign/<int:contact_id>/<int:campaign_id>/', unsubscribe_from_campaign, name="unsubscribe_from_campaign"),
    path('contacts/<int:contact_id>/view/', contact_detail, name="contact_detail"),
    path('download-contacts-for-campaign/<int:compaign_id>/', download_contacts_for_campaign, name="download_contacts_for_campaign"),
    path('create-campaign-from-template/<int:template_id>/', create_campaign_from_template, name="create_campaign_from_template"),
    path('download-links-clicked/<int:campaign_id>/', download_links_clicked, name="download_links_clicked"),
    path('delete_multiple_contacts/', delete_multiple_contacts, name="delete_multiple_contacts"),
    path('download-failed-contacts/<int:contact_list_id>/', download_failed_contacts, name="download_failed_contacts"),
    path('delete_all_contacts/<int:contact_list_id>/', delete_all_contacts, name="delete_all_contacts"),
    path('add-email-for-campaigns/', add_email_for_campaigns, name="add_email_for_campaigns"),
    path('list-all-emails-for-campaigns/', list_all_emails_for_campaigns, name="list_all_emails_for_campaigns"),
    path('edit-email-for-campaigns/<int:pk>/', edit_email_for_campaigns, name="edit_email_for_campaigns"),
    path('delete-email-for-campaigns/<int:pk>/', delete_email_for_campaigns, name="delete_email_for_campaigns"),

    path('add-blocked-domain/', add_blocked_domain, name="add_blocked_domain"),
    path('blocked-domain-list/', blocked_domain_list, name="blocked_domain_list"),
    path('edit-blocked-domain/<int:blocked_domain_id>/', edit_blocked_domain, name="edit_blocked_domain"),
    path('delete-blocked-domain/<int:blocked_domain_id>/', delete_blocked_domain, name="delete_blocked_domain"),

    path('add-blocked-email/', add_blocked_email, name="add_blocked_email"),
    path('blocked-email-list/', blocked_email_list, name="blocked_email_list"),
    path('edit-blocked-email/<int:blocked_email_id>/', edit_blocked_email, name="edit_blocked_email"),
    path('delete-blocked-email/<int:blocked_email_id>/', delete_blocked_email, name="delete_blocked_email"),

    # path('search-marketing-contact-emails/', include('haystack.urls')),
    # path('elastic-search/', contacts_list_elastic_search),
]

marketing/models.py
import arrow
import os
from datetime import datetime, timedelta
from django.db import models
from django.utils.timesince import timesince
from django.utils.translation import ugettext_lazy as _
from django.core.validators import RegexValidator
from django.dispatch import receiver
from django.db.models import Sum
from django.template.defaultfilters import slugify
from common.models import User
from common.utils import convert_to_custom_timezone


class Tag(models.Model):
    name = models.CharField(max_length=500)
    color = models.CharField(max_length=20,
                             default="#999999", verbose_name=_("color"))
    created_by = models.ForeignKey(User,
                                   related_name="marketing_tags",
                                   null=True, on_delete=models.SET_NULL)
    created_on = models.DateTimeField(auto_now_add=True)

    @property
    def created_by_user(self):
        return self.created_by if self.created_by else None


class EmailTemplate(models.Model):
    created_by = models.ForeignKey(
        User, related_name="marketing_emailtemplates",
        null=True, on_delete=models.SET_NULL)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=5000)
    subject = models.CharField(max_length=5000)
    html = models.TextField()

    class Meta:
        ordering = ['id', ]

    @property
    def created_by_user(self):
        return self.created_by if self.created_by else None

    @property
    def created_on_arrow(self):
        return arrow.get(self.created_on).humanize()


class ContactList(models.Model):
    created_by = models.ForeignKey(
        User, related_name="marketing_contactlist",
        null=True, on_delete=models.SET_NULL)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=500)
    tags = models.ManyToManyField(Tag)
    # is_public = models.BooleanField(default=False)
    visible_to = models.ManyToManyField(
        User, related_name="contact_lists_visible_to")

    class Meta:
        ordering = ('-created_on',)

    @property
    def created_by_user(self):
        return self.created_by if self.created_by else None

    @property
    def created_on_format(self):
        return self.created_on.strftime('%b %d, %Y %I:%M %p')

    # @property
    # def created_on_since(self):
    #     now = datetime.now()
    #     difference = now.replace(tzinfo=None) - \
    #         self.created_on.replace(tzinfo=None)

    #     if difference <= timedelta(minutes=1):
    #         return 'just now'
    #     return '%(time)s ago' % {
    #         'time': timesince(self.created_on).split(', ')[0]}

    @property
    def tags_data(self):
        return self.tags.all()

    @property
    def no_of_contacts(self):
        return self.contacts.all().count()

    @property
    def no_of_campaigns(self):
        return self.campaigns.all().count()

    @property
    def unsubscribe_contacts(self):
        return self.contacts.filter(is_unsubscribed=True).count()

    @property
    def bounced_contacts(self):
        return self.contacts.filter(is_bounced=True).count()

    # @property
    # def no_of_clicks(self):
    #     clicks = CampaignLog.objects.filter(
    #         contact__contact_list__in=[self]).aggregate(Sum(
    #             'no_of_clicks'))['no_of_clicks__sum']
    #     return clicks

    @property
    def created_on_arrow(self):
        return arrow.get(self.created_on).humanize()

    @property
    def updated_on_arrow(self):
        return arrow.get(self.updated_on).humanize()


class Contact(models.Model):
    phone_regex = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',
        message="Phone number must be entered in the format: '+999999999'. \
        Up to 20 digits allowed."
    )
    created_by = models.ForeignKey(
        User, related_name="marketing_contacts_created_by",
        null=True, on_delete=models.SET_NULL)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    contact_list = models.ManyToManyField(ContactList, related_name="contacts")
    name = models.CharField(max_length=500)
    email = models.EmailField()
    contact_number = models.CharField(
        validators=[phone_regex], max_length=20, blank=True, null=True)
    is_unsubscribed = models.BooleanField(default=False)
    is_bounced = models.BooleanField(default=False)
    company_name = models.CharField(max_length=500, null=True, blank=True)
    last_name = models.CharField(max_length=500, null=True, blank=True)
    city = models.CharField(max_length=500, null=True, blank=True)
    state = models.CharField(max_length=500, null=True, blank=True)
    contry = models.CharField(max_length=500, null=True, blank=True)

    def __str__(self):
        return self.email

    @property
    def created_on_arrow(self):
        return arrow.get(self.created_on).humanize()

    class Meta:
        ordering = ['id', ]


class FailedContact(models.Model):
    phone_regex = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',
        message="Phone number must be entered in the format: '+999999999'.\
        Up to 20 digits allowed."
    )
    created_by = models.ForeignKey(
        User, related_name="marketing_failed_contacts_created_by", null=True,
        on_delete=models.SET_NULL)
    created_on = models.DateTimeField(auto_now_add=True)
    contact_list = models.ManyToManyField(
        ContactList, related_name="failed_contacts")
    name = models.CharField(max_length=500, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    contact_number = models.CharField(
        validators=[phone_regex], max_length=20, blank=True, null=True)
    company_name = models.CharField(max_length=500, null=True, blank=True)
    last_name = models.CharField(max_length=500, null=True, blank=True)
    city = models.CharField(max_length=500, null=True, blank=True)
    state = models.CharField(max_length=500, null=True, blank=True)
    contry = models.CharField(max_length=500, null=True, blank=True)

    def __str__(self):
        return self.email

    @property
    def created_on_arrow(self):
        return arrow.get(self.created_on).humanize()


def get_campaign_attachment_path(self, filename):
    file_split = filename.split('.')
    file_extension = file_split[-1]
    path = "%s_%s" % (file_split[0], str(datetime.now()))
    return "campaigns/attachment/" + slugify(path) + "." + file_extension


class Campaign(models.Model):
    STATUS_CHOICES = (
        ('Scheduled', 'Scheduled'),
        ('Cancelled', 'Cancelled'),
        ('Sending', 'Sending'),
        ('Preparing', 'Preparing'),
        ('Sent', 'Sent'),
    )

    title = models.CharField(max_length=5000)
    created_by = models.ForeignKey(
        User, related_name="marketing_campaigns_created_by",
        null=True, on_delete=models.SET_NULL)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    contact_lists = models.ManyToManyField(
        ContactList, related_name="campaigns")
    email_template = models.ForeignKey(
        EmailTemplate, blank=True, null=True, on_delete=models.SET_NULL)
    schedule_date_time = models.DateTimeField(blank=True, null=True)
    timezone = models.CharField(max_length=100, default='UTC')
    reply_to_email = models.EmailField(blank=True, null=True)
    subject = models.CharField(max_length=5000)
    html = models.TextField()
    html_processed = models.TextField(default="", blank=True)
    from_email = models.EmailField(blank=True, null=True)
    from_name = models.EmailField(blank=True, null=True)
    sent = models.IntegerField(default='0', blank=True)
    opens = models.IntegerField(default='0', blank=True)
    opens_unique = models.IntegerField(default='0', blank=True)
    bounced = models.IntegerField(default='0')
    tags = models.ManyToManyField(Tag)
    status = models.CharField(
        default="Preparing", choices=STATUS_CHOICES, max_length=20)
    attachment = models.FileField(
        max_length=1000, upload_to=get_campaign_attachment_path, blank=True, null=True)

    class Meta:
        ordering = ('-created_on', )

    # @property
    # def no_of_unsubscribers(self):
    #     unsubscribers = self.campaign_contacts.filter(
    #         contact__is_unsubscribed=True).count()
    #     return unsubscribers

    # @property
    # def no_of_bounces(self):
    #     bounces = self.campaign_contacts.filter(
    #         contact__is_bounced=True).count()
    #     return bounces

    @property
    def no_of_clicks(self):
        clicks = self.marketing_links.aggregate(Sum('clicks'))['clicks__sum']
        return clicks

    # @property
    # def no_of_sent_emails(self):
    #     contacts = self.campaign_contacts.count()
    #     return contacts

    # @property
    # def created_on_format(self):
    #     return self.created_on.strftime('%b %d, %Y %I:%M %p')

    @property
    def sent_on_format(self):
        if self.schedule_date_time:
            c_schedule_date_time = convert_to_custom_timezone(
                self.schedule_date_time, self.timezone)
            return c_schedule_date_time.strftime('%b %d, %Y %I:%M %p')
        else:
            c_created_on = convert_to_custom_timezone(
                self.created_on, self.timezone)
            return c_created_on.strftime('%b %d, %Y %I:%M %p')

    @property
    def get_all_emails_count(self):
        email_count = CampaignLog.objects.filter(campaign=self).count()
        return email_count
        # return self.contact_lists.exclude(contacts__email=None).values_list('contacts__email').count()

    @property
    def get_all_email_bounces_count(self):
        # return self.contact_lists.filter(contacts__is_bounced=True

templates/marketing/email_template/details.html
{% extends 'marketing/base.html' %}
{% load staticfiles %}
{% load paginate %}
{% block extralinks %}
<style>
  .detail {
    font-size: 2em;
  }
</style>
{% endblock %}
{% block content %}
{{ block.super }}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb mb-3">
    <li class="breadcrumb-item"><a href="{% url 'marketing:email_template_list' %}">Email Template</a></li>
    <li class="breadcrumb-item active">{{email_template.title}}</li>
  </ol>
</nav>
<div class="main_container ml-5 mr-5">
  <div class="row marl">
    <div class="col-md-12">
      <b class="bold detail">Title</b>
      <p>{{email_template.title}}</p>
      <b class="detail">Subject </b>
      <p>{{email_template.subject}}</p>
      <b class="detail">Body </b>
      

      <div id="editor-container">
        {{ email_template.html|safe }}
      </div>
    </div>
  </div>
</div>
{% endblock %}


{% block js_block %}
<script>

  var quill = new Quill('#editor-container', {
    modules: {
      toolbar: [
        ['code-block']
      ]
    },
    theme: 'snow'
  });
  quill.disable();

  $('.ql-toolbar').hide();
  $('#editor-container').css('border', 'none');
  $('.ql-editor').css('margin', '0');
  $('.ql-editor').css('padding', '0');
  // $('#editor-container').css('height','0');

</script>
{% endblock js_block %}

templates/marketing/email_template/index.html
{% extends 'marketing/base.html' %}
{% load staticfiles %}
{% load paginate %}
{% block content %}
{{ block.super }}
<div class="main_container ml-5 mr-5">
  <div class="row marl">

    <div class="filter_row list_filter_row row marl col-md-12 mb-2">
      <div class="">
        <div class="card">
          <div class="card-body">
            <form id="leads_filter" action="" method="POST">
              <div class="card-body ">
                <div class="card-title">Filters</div>
                <div class="row marl">
                  <div class="filter_col col-md-3">
                    <div class="form-group">
                      <label for="exampleInputEmail1">Name</label>
                      <input type="text" class="form-control" placeholder="Template Name" name="template_name"
                        value="{{request.POST.template_name}}">
                    </div>
                  </div>
                  <div class="filter_col col-md-3">
                    <div class="form-group">
                      <label for="exampleInputEmail1">Created By</label>
                      <select name="created_by" id="created_by" class="assigned_users_ form-control">
                        <option value="">
                          ------------------</option>
                        {% for user in users %}
                        <option value="{{user.id}}" {% if user.id|slugify == request.POST.created_by %} selected=""
                          {% endif %}>
                          {{user.email}}</option>
                        {% endfor %}
                      </select>
                    </div>
                  </div>
                  <input type="hidden" name="tab_status" id="tab_status">
                  <div class="filter_col col-2">
                    <div class="form-group buttons_row">
                      <button class="btn btn-primary save" type="submit">Search</button>
                      <a href="" class="btn btn-default clear" onclick="window.location.reload">Clear</a>
                    </div>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-12">
      <div class="table_container_row no_mar_top">
        <div class="card">
          <div class="card-body">
            <div class="card-title text-right">
              <span class="float-left">Email Templates - {{email_templates|length}}</span>
              <span class="filter_toggle">
                <a href="#" class="primary_btn"><i class="fas fa-filter"></i></a>
              </span>
              <a href="{% url 'marketing:email_template_new' %}" class="primary_btn">Add New Email Template</a>
            </div>
            <div class="table-responsive table-bordered ">
              <table class="table">
                {% if email_templates %}
                <thead>
                  <tr>
                    <th width="5%" class="text-center">S. No</th>
                    <th width="20%" class="text-center">Template Name</th>
                    <th width="15%" class="text-center">Created By</th>
                    <th width="10%" class="text-center">Created On</th>
                    <th width="10%" class="text-center">Create Campaign</th>
                    
                    <th width="15%" class="text-center">Actions</th>
                  </tr>
                </thead>
                {% endif %}
                <tbody>
                  {% if per_page %}
                  {% paginate per_page email_templates %}
                  {% else%}
                  {% paginate 10 email_templates %}
                  {% endif %}
                  {% for email_template in email_templates %}
                  <tr style="text-align:center;">
                    <td class="text-center" scope="row">{{ forloop.counter }}</td>
                    <td scope="row"><a
                        href="{% url 'marketing:email_template_detail' email_template.id %}">{{ email_template.title }}</a>
                    </td>
                    <td scope="row">{{ email_template.created_by }}</td>
                    <td scope="row" title="{{ email_template.created_on }}">{{ email_template.created_on_arrow }}</td>
                    <td class="text-center"><a
                        href="{% url 'marketing:create_campaign_from_template' email_template.id %}" class="a_color"
                        data-toggle="tooltip" data-placement="bottom"
                        title="Create a new campaign with this template"><i class="fas fa-calendar-plus"></i></a></td>
                    
                    <td class="actions text-center">
                      <a href="{% url 'marketing:email_template_detail' email_template.id %}"
                        class="btn btn-info edit" title="View" ><i class="fas fa-eye"></i></a>
                      <a href="{% url 'marketing:email_template_edit' email_template.id %}"
                        class="btn btn-success edit" title="Edit" ><i class="fas fa-edit"></i></a>
                      <a href="{% url 'marketing:email_template_delete' email_template.id %}"
                        class="btn btn-danger delete remove_account" title="Delete"><i class="fas fa-trash"></i></a>
                    </td>
                  </tr>
                  {% empty %}
                  <tr>
                    <td colspan="4">No Records Found!</td>
                  </tr>
                  {% endfor %}
                  

                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="marl row text-center mt-5">
    {% show_pages %}
  </div>
</div>
{% endblock %}
{% block js_block %}
<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
    $(".filter_toggle").click(function () {
      $(".list_filter_row").toggle();
    });

    search = "{{search}}"
    alert(search)
    if (search == 'True') {
    $(".list_filter_row").show();
    }

    $('#id_tag').select2();
    $('#created_by').select2();

    $(".remove_account").click(function (e) {
      e.preventDefault()
      url = $(this).attr('href')
      if (!confirm('Are you sure you want to delete?'))
        return;
      window.location = $(this).attr('href')
    })

    $("a[rel='page']").click(function (e) {
      e.preventDefault();
      $('#leads_filter').attr("action", $(this).attr("href"));
      $('#leads_filter').submit();
    });
  })
</script>
{% endblock js_block %}

templates/marketing/email_template/new.html
{% extends 'marketing/base.html' %}
{% load staticfiles %}
{% block content %}
{{ block.super }}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb mb-3">
    <li class="breadcrumb-item"><a href="{% url 'marketing:email_template_list' %}">Email Template</a></li>
    <li class="breadcrumb-item active">{% if email_template %}Edit{% else %}Create{% endif %} Email Template</li>
  </ol>
</nav>
<div class="main_container ml-5 mr-5">
  <div class="row marl">
    <div class="col-md-12">
      <form id="add_form" method="POST" action='' novalidate>
        <div class="overview_form_block row marl justify-content-center">
          <div class="col-md-12">
            <div class="card">
              <div class="card-body">
                <div class="card-title text-center">
                  {% if email_template %}Edit{% else %}Create{% endif %} Email Template
                </div>
                <form>
                  <div class="row marl">
                    <div class="col-md-12">
                      <div class="form-group">
                        <label for="">Title</label><span class="error_marker" style="color:red"> *</span>
                        <input type="text" class="form-control" name="title"
                          value="{% if email_template %}{{ email_template.title }}{% endif %}"
                          placeholder="Enter Template Title">
                      </div>
                      <span id="id_title"></span>
                    </div>
                    <div class="col-md-12">
                      <div class="form-group">
                        <label for="">Subject</label><span class="error_marker" style="color:red"> *</span>
                        <input type="text" class="form-control" name="subject"
                          value="{% if email_template %}{{ email_template.subject }}{% endif %}"
                          placeholder="Enter Template Subject">
                      </div>
                      <span id="id_subject"></span>
                    </div>
                    <div class="col-md-12">
                      <div class="form-group">
                        <label>HTML Code</label><span class="error_marker" style="color:red"> *</span>
                        <div id="editor-container">
                          {% if email_template %}{{ email_template.html|safe }}{% endif %}
                        </div>
                      </div>
                      <input type="hidden" name="html" id="html_content">
                      <span id="id_html"></span>
                    </div>
                    
                    <div class="col-md-12 text-center">
                      <div class="row marl buttons_row text-center form_btn_row">
                        <button type="submit" class="btn btn-default save">Save
                          Template</button>
                        <a href="{% url 'marketing:email_template_list' %}" class="btn btn-default clear">Cancel</a>
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}
{% block js_block %}
<script src="{% static 'js/ajaxForm.js' %}"></script>

<script>
  var quill = new Quill('#editor-container', {
    modules: {
      toolbar: [
        [{ header: [1, 2, false] }],
        ['bold', 'italic', 'underline'],
        ['code-block', 'link']
      ]
    },
    placeholder: 'Compose an epic...',
    theme: 'snow' // or 'bubble'
  });

  if (quill.root.innerHTML !== "<p><br></p>") {
    $('#html_content').val(quill.root.innerHTML);
  }


  var preciousContent = document.getElementById('myPrecious');
  var justTextContent = document.getElementById('justText');
  var justHtmlContent = document.getElementById('justHtml');

  quill.on('text-change', function () {
    $('.ql-syntax').css({"background-color":"#23241f","color":"#f8f8f2","overflow":"visible","border-radius":"3px","white-space":"pre-wrap","margin-bottom":"5px","margin-top":"5px","padding":"5px 10px"})
    var delta = quill.getContents();
    var text = quill.getText();
    var justHtml = quill.root.innerHTML;
		/*preciousContent.innerHTML = JSON.stringify(delta);
		justTextContent.innerHTML = text;
		justHtmlContent.innerHTML = justHtml;*/
    $('#html_content').val(justHtml);
  });


  $('.save_btn').click(function (e) {
    e.preventDefault();
    $("form#add_form").submit()
  })

  $('form#add_form').ajaxForm({
    type: 'POST',
    dataType: 'json',
    url: $(this).attr('action'),
    data: $(this).serialize(),
    beforeSend: function (e) {
      $('.ql-syntax').css({"background-color":"#23241f","color":"#f8f8f2","overflow":"visible","border-radius":"3px","white-space":"pre-wrap","margin-bottom":"5px","margin-top":"5px","padding":"5px 10px"})
    },
    success: function (data) {
      console.log("data", data)
      if (data.error == false) {
        window.location = "{% url 'marketing:email_template_list' %}";
      } else {
        /*$(document).ajaxStop($.unblockUI);*/
        // $.unblockUI();
        $('p.failure').remove();
        for (var key in data.errors) {
          $('#id_' + key).html('<p class="error failure"> *' + data.errors[key] + '</p>');
        }
      }
    },
    error: function (xhr, errmsg, err) {
      console.log('error data', errmsg, err)
    }
  });
</script>
{% endblock js_block %}