common/urls.py
from django.contrib.auth import views as auth_views

from django.urls import path
from common.views import (
    HomeView, LoginView, ForgotPasswordView, LogoutView,
    ChangePasswordView, ProfileView,
    UsersListView, CreateUserView, UpdateUserView, UserDetailView,
    UserDeleteView, PasswordResetView,
    DocumentListView, document_create, document_update,
    DocumentDetailView, DocumentDeleteView,get_teams_and_users,
    download_document, change_user_status, download_attachment,
    add_comment, edit_comment, remove_comment,
    api_settings, add_api_settings, view_api_settings,
    update_api_settings, delete_api_settings,
    change_passsword_by_admin, google_login, create_lead_from_site,
    activate_user, resend_activation_link
)
from django.conf.urls.static import static
from django.conf import settings

app_name = 'common'


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('forgot-password/',
         ForgotPasswordView.as_view(), name='forgot_password'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change-password/',
         ChangePasswordView.as_view(), name='change_password'),
    path('profile/', ProfileView.as_view(), name='profile'),

    # User views
    path('users/list/', UsersListView.as_view(), name='users_list'),
    path('users/create/', CreateUserView.as_view(), name='create_user'),
    path('users/<int:pk>/edit/', UpdateUserView.as_view(), name="edit_user"),
    path('users/<int:pk>/view/', UserDetailView.as_view(), name='view_user'),
    path('users/<int:pk>/delete/',
         UserDeleteView.as_view(), name='remove_user'),

    path(
        'password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    # Document
    path('documents/', DocumentListView.as_view(), name='doc_list'),
    path('documents/create/', document_create, name='create_doc'),
    path('documents/<int:pk>/edit/', document_update, name="edit_doc"),
    path('documents/<int:pk>/view/',
         DocumentDetailView.as_view(), name='view_doc'),
    path('documents/<int:pk>/delete/',
         DocumentDeleteView.as_view(), name='remove_doc'),

    # download
    path('documents/<int:pk>/download/',
         download_document, name='download_document'),

    # download_attachment
    path('attachments/<int:pk>/download/',
         download_attachment, name='download_attachment'),

    path('user/status/<int:pk>/',
         change_user_status, name='change_user_status'),

    path('comment/add/', add_comment, name="add_comment"),
    path('comment/<int:pk>/edit/', edit_comment, name="edit_comment"),
    path('comment/remove/', remove_comment, name="remove_comment"),

    # settings
    path('api/settings/', api_settings, name="api_settings"),
    path('api/settings/add/', add_api_settings, name="add_api_settings"),
    path('api/settings/<int:pk>/',
         view_api_settings, name="view_api_settings"),
    path('api/settings/<int:pk>/update/',
         update_api_settings, name="update_api_settings"),
    path('api/settings/<int:pk>/delete/',
         delete_api_settings, name="delete_api_settings"),

    path('change-password-by-admin/', change_passsword_by_admin,
         name="change_passsword_by_admin"),
    path('google/login/', google_login, name="google_login"),
    path('create-lead-from-site/', create_lead_from_site,
         name='create_lead_from_site'),

    # user activate link
    path('activate-user/<uidb64>/<token>/<activation_key>/', activate_user, name='activate_user'),
    path('resend_activation_link/<userId>/', resend_activation_link, name='resend_activation_link'),
    path('get_teams_and_users/', get_teams_and_users, name="get_teams_and_users")



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from django.urls import include, path
from common.views import handler404, handler500

app_name = 'crm'

urlpatterns = [
    path('', include('common.urls', namespace="common")),
    path('', include('django.contrib.auth.urls')),
    path('marketing/', include('marketing.urls', namespace="marketing")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('leads/', include('leads.urls', namespace="leads")),
    path('contacts/', include('contacts.urls', namespace="contacts")),
    path('opportunities/',
         include('opportunity.urls', namespace="opportunities")),
    path('cases/', include('cases.urls', namespace="cases")),
    path('tasks/', include('tasks.urls', namespace="tasks")),
    path('invoices/', include('invoices.urls', namespace="invoices")),
    path('events/', include('events.urls', namespace="events")),
    path('teams/', include('teams.urls', namespace="teams")),
    path('emails/', include('emails.urls', namespace="emails")),
    # path('planner/', include('planner.urls', namespace="planner")),
    path('logout/', views.LogoutView, {'next_page': '/login/'}, name="logout"),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = handler404
handler500 = handler500

marketing/urls.py
from django.urls import path, include
from .views import (
    dashboard, contact_lists, contacts_list, contact_list_new, contact_list_detail, edit_contact,
    email_template_list, email_template_new, email_template_edit, email_template_delete,
    email_template_detail, campaign_list, campaign_new, campaign_details, campaign_delete,
    edit_contact_list, failed_contact_list_download_delete,
    campaign_link_click, campaign_open, demo_file_download, delete_contact, unsubscribe_from_campaign, contact_detail,
    download_contacts_for_campaign, create_campaign_from_template,
    download_links_clicked, delete_multiple_contacts, download_failed_contacts, delete_all_contacts,
    add_email_for_campaigns, list_all_emails_for_campaigns, edit_email_for_campaigns, delete_email_for_campaigns,
    add_blocked_domain, blocked_domain_list, edit_blocked_domain, delete_blocked_domain,
    add_blocked_email, blocked_email_list, edit_blocked_email, delete_blocked_email,
    contacts_list_elastic_search,
    # MarketingContactEmailSearch,
    # contacts_list_new
    # delete_contact_list
    # campaign_edit
    # edit_failed_contact
    # delete_failed_contact
    # failed_contact_list_detail
)

app_name = 'marketing'

urlpatterns = [
    path('', dashboard, name='dashboard'),

    path('contact-list/', contact_lists, name='contact_lists'),
    path('contacts/<int:pk>/edit/', edit_contact, name='edit_contact'),
    path('contacts/<int:pk>/delete/', delete_contact, name='delete_contact'),
    path('contacts/', contacts_list_elastic_search, name='contacts_list'),
    path('contact-list/create/', contact_list_new, name='contact_list_new'),
    # path('cl/list/cnew/', contacts_list_new, name='contacts_list_new'),
    path('contact-list/<int:pk>/detail/', contact_list_detail, name='contact_list_detail'),
    # path('contact-list/<int:pk>/failed/', failed_contact_list_detail, name='failed_contact_list_detail'),
    # path('contact-list/<int:pk>/failed/edit/', edit_failed_contact, name='edit_failed_contact'),
    # path('contact-list/<int:pk>/failed/delete/', delete_failed_contact, name='delete_failed_contact'),
    path('contact-list/<int:pk>/failed/download/',
         failed_contact_list_download_delete, name='failed_contact_list_download_delete'),
    path('contact-list/<int:pk>/edit/', edit_contact_list, name='edit_contact_list'),
    # path('cl/list/<int:pk>/delete/', delete_contact_list, name='delete_contact_list'),

    path('email-templates/', email_template_list, name='email_template_list'),
    path('email-templates/create/', email_template_new, name='email_template_new'),
    path('email-templates/<int:pk>/edit/', email_template_edit, name='email_template_edit'),
    path('email-templates/<int:pk>/detail/', email_template_detail, name='email_template_detail'),
    path('email-templates/<int:pk>/delete/', email_template_delete, name='email_template_delete'),

    path('campaigns/', campaign_list, name='campaign_list'),
    path('campaigns/create/', campaign_new, name='campaign_new'),
    # path('cm/<int:pk>/edit/', campaign_edit, name='campaign_edit'),
    path('campaigns/<int:pk>/details/', campaign_details, name='campaign_details'),
    path('campaigns/<int:pk>/delete/', campaign_delete, name='campaign_delete'),
    path('cm/link/<int:link_id>/e/<int:email_id>/', campaign_link_click, name='campaign_link_click'),
    path('cm/track-email/<int:campaign_log_id>/contact/<int:email_id>/', campaign_open, name='campaign_open'),
    path('demo-file-download-for-contacts-list/', demo_file_download, name='demo_file_download'),
    path('unsubscribe-from-campaign/<int:contact_id>/<int:campaign_id>/', unsubscribe_from_campaign, name="unsubscribe_from_campaign"),
    path('contacts/<int:contact_id>/view/', contact_detail, name="contact_detail"),
    path('download-contacts-for-campaign/<int:compaign_id>/', download_contacts_for_campaign, name="download_contacts_for_campaign"),
    path('create-campaign-from-template/<int:template_id>/', create_campaign_from_template, name="create_campaign_from_template"),
    path('download-links-clicked/<int:campaign_id>/', download_links_clicked, name="download_links_clicked"),
    path('delete_multiple_contacts/', delete_multiple_contacts, name="delete_multiple_contacts"),
    path('download-failed-contacts/<int:contact_list_id>/', download_failed_contacts, name="download_failed_contacts"),
    path('delete_all_contacts/<int:contact_list_id>/', delete_all_contacts, name="delete_all_contacts"),
    path('add-email-for-campaigns/', add_email_for_campaigns, name="add_email_for_campaigns"),
    path('list-all-emails-for-campaigns/', list_all_emails_for_campaigns, name="list_all_emails_for_campaigns"),
    path('edit-email-for-campaigns/<int:pk>/', edit_email_for_campaigns, name="edit_email_for_campaigns"),
    path('delete-email-for-campaigns/<int:pk>/', delete_email_for_campaigns, name="delete_email_for_campaigns"),

    path('add-blocked-domain/', add_blocked_domain, name="add_blocked_domain"),
    path('blocked-domain-list/', blocked_domain_list, name="blocked_domain_list"),
    path('edit-blocked-domain/<int:blocked_domain_id>/', edit_blocked_domain, name="edit_blocked_domain"),
    path('delete-blocked-domain/<int:blocked_domain_id>/', delete_blocked_domain, name="delete_blocked_domain"),

    path('add-blocked-email/', add_blocked_email, name="add_blocked_email"),
    path('blocked-email-list/', blocked_email_list, name="blocked_email_list"),
    path('edit-blocked-email/<int:blocked_email_id>/', edit_blocked_email, name="edit_blocked_email"),
    path('delete-blocked-email/<int:blocked_email_id>/', delete_blocked_email, name="delete_blocked_email"),

    # path('search-marketing-contact-emails/', include('haystack.urls')),
    # path('elastic-search/', contacts_list_elastic_search),
]

templates/marketing/base.html
{% extends 'root.html' %}

{% block main_menu %}
<ul class="navbar-nav mr-auto">
  
  {% if request.user.is_superuser or request.user.role == 'ADMIN' or request.user.has_marketing_access %}
  <li class="nav-item"><a class="nav-link" id="marketing-dashboard" href="{% url 'marketing:dashboard' %}">Dashboard</a>
  </li>
  <li class="nav-item mt-2 contact_class" id="contact">
    <div class="btn-group">
      <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false" style="box-shadow: none; color: #657b88">
        Contacts
      </button>
      <div class="dropdown-menu mt-2">
        <a class="dropdown-item contact-list" id="contact-list" href="{% url 'marketing:contact_lists' %}">Contacts
          List</a>
        
        <a class="dropdown-item contacts" id="contacts" href="{% url 'marketing:contacts_list' %}">Contacts</a>
        
      </div>
    </div>
  </li>

  
  <li class="nav-item"><a class="nav-link" id="email-templates" href="{% url 'marketing:email_template_list' %}">Email
      templates</a></li>
  <li class="nav-item"><a class="nav-link" id="campaigns" href="{% url 'marketing:campaign_list' %}">Campaigns</a></li>
  {% endif %}
  
</ul>
{% endblock %}



{% comment %}


{% extends 'root.html' %}
{% load staticfiles %}
{% load compress %}
{% load thumbnail %}
{% block main_menu %}

{% endblock %}
{% block header %}

{% endblock header %}


{% block content %}
<div class="side_menu">
  
  
  <div class="dropdown">
    <a class="dropdown-toggle navbar-brand mt-2 ml-3" href="#" role="button" id="dropdownMenuLink"
      data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
      style="color:#000; font-weight: 800; font-size: 1.5em;">
      Django <span class="green_color text-uppercase" style="color:#7ae847">Crm</span>
    </a>

    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
      <a class="dropdown-item" href="/">Sales</a>
      <a class="dropdown-item" href="{% url 'marketing:dashboard' %}">Marketing</a>
    </div>
  </div>
  
  <div class="profile_block">
    <ul>

      <li data-toggle="tooltip" data-placement="bottom" title="{{request.user}}">
        <a href="#" class="profile_pic">
          
          {% if not request.user.profile_pic %}
          <img src="{% static 'images/user.png' %}" alt="Micro profile pic">
          {% else %}
          {% thumbnail request.user.profile_pic "25x25" as im %}
          <img src="{{ im.url }}">
          {% endthumbnail %}
          {% endif %}
        </a>
      </li>

      <li data-toggle="tooltip" data-placement="bottom" title="Users">
        <a href="{% url 'common:users_list' %}" class="sky_blue box"><i class="fas fa-users"></i>
        </a>
      </li>
      <li data-toggle="tooltip" data-placement="bottom" title="Change Password">
        <a href="{% url 'common:change_password' %}" class="red box"><i class="fas fa-key"></i></a>
      </li>
      <li data-toggle="tooltip" data-placement="bottom" title="Profile">
        <a href="{% url 'common:profile' %}" class="green box"><i class="fas fa-user"></i></a>
      </li>
      <li data-toggle="tooltip" data-placement="bottom" title="Logout">
        <a href="{% url 'common:logout' %}" class="purple box"><i class="fas fa-sign-out-alt"></i></a>
      </li>
    </ul>
  </div>
  <div class="menu_block">
    <ul class="main_menu">
      <li class="parent_menu">
        <a href="{% url 'marketing:contact_lists' %}" class="red"><i class="far fa-address-book"></i>Contacts</a>
        <ul class="submenu">
          <li><a href="{% url 'marketing:contacts_list' %}" class="yellow"><i class="fas fa-bars"></i>All Contacts</a>
          </li>
          <li><a href="{% url 'marketing:contact_list_new' %}" class="yellow"><i class="far fa-plus-square"></i>Create
              Contact</a></li>
        </ul>
      </li>
      <li class="parent_menu">
        <a href="{% url 'marketing:email_template_list' %}" class="purple"><i class="fas fa-envelope-open"></i>Email
          Templates</a>
        <ul class="submenu">
          <li><a href="{% url 'marketing:email_template_list' %}" class="d_green"><i class="fas fa-bars"></i>All
              Templates</a></li>
          <li><a href="{% url 'marketing:email_template_new' %}" class="d_green"><i
                class="far fa-plus-square"></i>Create
              Template</a></li>
        </ul>
      </li>
      <li class="parent_menu">
        <a href="{% url 'marketing:campaign_list' %}" class="green"><i class="fas fa-at"></i>Campaigns</a>
        <ul class="submenu">
          <li><a href="{% url 'marketing:campaign_list' %}" class="sky_color"><i class="fas fa-bars"></i>All
              Campaigns</a></li>
          <li><a href="{% url 'marketing:campaign_new' %}" class="sky_color"><i class="far fa-plus-square"></i>Create
              Campaign</a></li>
        </ul>
      </li>
    </ul>
  </div>
</div>

{% endblock %}

{% endcomment %}

templates/marketing/dashboard.html
{% extends 'marketing/base.html' %}
{% load staticfiles %}
{% load common_tags %}
{% load paginate %}
{% block extralinks %} 
<style>
  .modebar {
    display: none
  }

  .text_ellipsis {
    width: 22em;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  .text_ellipsis_1 {

    width: 20em;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
</style>
{% endblock %}
{% block content %}
{{ block.super }}
<div class="" style="">
  <div class="row marl">
    <div class="col-md-12">
      


      <div class="row marl justify-content-center">
        <div class="col-md-9">
          
          <div class="row count_blocks_row">
            <div class="col-md-3">
              <div class="item sky_blue">
                <a href="{% url 'marketing:email_template_list'%}">
                  <div class="title">Email Templates</div>
                  <div class="count">{{email_templates|length}}</div>
                  
                </a>
              </div>
            </div>
            <div class="col-md-3">
              <div class="item green">
                <a href="{% url 'marketing:contact_lists' %}">
                  <div class="title">Contacts List</div>
                  <div class="count">{{contacts_list|length}}</div>
                </a>
                
              </div>
            </div>
            <div class="col-md-3">
              <div class="item red">
                <a href="{% url 'marketing:contacts_list' %}">
                  <div class="title">Contacts</div>
                  <div class="count">{{contacts|length}}</div>
                  
                </a>
              </div>
            </div>
            <div class="col-md-3">
              <div class="item yellow">
                <a href="{% url 'marketing:campaign_list' %}">
                  <div class="title">Campaigns</div>
                  <div class="count">{{campaigns|length}}</div>
                  
                </a>
              </div>
            </div>
          </div>
          
          <div class="open_sections row">

            <div class="col-md-12">
              <div class="" id="graph">
                
              </div>
            </div>


            <div class="col-md-6 table_container_row">
              <div class="card">
                <div class="card-body">
                  <div class="card-title">
                    <span>Contacts List</span>
                  </div>
                  <div class="table-responsive">
                    {% if contacts_list %}
                    <table class="table">
                      <thead>
                        <tr>
                          <th width="40%">Name</th>
                          
                          <th width="50%">Tags</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for contact in contacts_list|slice:"5" %}
                        <tr>
                          <td>
                            <div class="text_ellipsis">
                            <a href="{% url 'marketing:contact_list_detail' contact.id %}">{{contact.name}}</a>
                          </div>
                          </td>
                          
                          <td style="display: block;">
                            {% for tag in contact.tags.all|slice:'3' %}
                            <span class="text-left color{{forloop.counter}} tag_class_cl" id="list_tag"
                              data-link="{{tag.id}}" style="cursor: pointer;">{{tag.name}}</span>
                            {% empty %}
                            <span class="text-left">No Tags</span>
                            {% endfor %}
                            {% if contact.tags.all|length > 3 %}
                            <a href="{% url 'marketing:contact_list_detail' contact.id %}" style="color:white;"><span
                                class="text-left" id="list_tag">{{contact.tags.all|length|subtract:'3'}}<span>
                                  more
                                </span></a></span>
                            {% endif %}
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                    {% else %}
                    <p style="text-align:center">There are no records</p>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-6 table_container_row">
              <div class="card">
                <div class="card-body">
                  <div class="card-title">
                    <span>Campaigns</span>
                  </div>
                  <div class="table-responsive">
                    {% if campaigns %}
                    <table class="table">
                      <thead>
                        <tr>
                          <th width="30%">Title</th>
                          <th width="30%">Tags</th>
                          <th width="50%">Contact List</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for campaign in campaigns|slice:"5" %}
                        <tr>
                          <td>
                            <div class="text_ellipsis_1">
                            <a href="{% url 'marketing:campaign_details' campaign.id %}">{{campaign.title}}</a>
                          </div>
                          </td>

                          <td style="display: block;">
                            {% for tag in campaign.tags.all|slice:'3' %}
                            <span class="text-left color{{forloop.counter}} tag_class_camp" id="list_tag"
                              data-link="{{tag.id}}" style="cursor: pointer;">{{tag.name}}</span>
                            {% empty %}
                            <span class="text-left">No Tags</span>
                            {% endfor %}
                            {% if campaign.tags.all|length > 3 %}
                            <a href="{% url 'marketing:campaign_details' campaign.id %}" style="color: white;"><span
                                class="text-left" id="list_tag">{{campaign.tags.all|length|subtract:'3'}}<span>
                                  more
                                </span></a></span>
                            {% endif %}
                          </td>
                          <td>
                            {% with contacts_lists=campaign.contact_lists.all %}
                            {% for contact in contacts_lists|slice:'3'  %}
                            <div>
                              <div>
                                <span class="text-left" id="list_opp_users_">
                                  <a
                                    href="{% url 'marketing:contact_list_detail' contact.id %}">{{contact.name}}</a><span>
                              </div>
                              {% empty %}
                              <span class="text-left">None</span>
                              {% endfor %}
                              {% if contacts_lists|length > 3 %}
                              <div>
                                <a href="{% url 'marketing:campaign_details' campaign.id %}" style="color:white;">
                                    <span class="text-left" id="list_tag">{{contacts_lists|length|subtract:'3'}}<span>
                                    more
                                  </span></span>
                                  </a>
                              </div>
                              {% endif %}
                              {% endwith %}
                              {% endfor %}
                            </div>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                    {% else %}
                    <p style="text-align:center">There are no records</p>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

{% endblock %}
{% block js_block %}
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<script type="text/javascript">

  $(document).ready(function () {
    $(".tag_class_cl").click(function () {
      // $(".tag_class_opp").css('cursor', 'pointer')
      url = "{% url 'marketing:contact_lists' %}"
      url = url + "?tag=" + $(this).attr('data-link')
      window.location.href = url;
    });

    $(".tag_class_camp").click(function (e) {
      e.preventDefault()
      // $(".tag_class_opp").css('cursor', 'pointer')
      url = "{% url 'marketing:campaign_list' %}"
      url = url + "?tag=" + $(this).attr('data-link')
      window.location.href = url;
    });

    {% if campaigns|length %}

    var trace1 = {
      // x: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      // y: [20, 14, 25, 16, 18, 22, 19, 15, 12, 16, 14, 17],
      x:{{x_axis_titles|safe}},
      y:{{y_axis_unsubscribed}},
      type: 'bar',
      name: 'Unsubscribed',
      marker: {
        color: 'rgb(49,130,189)',
        opacity: 0.7
      }
    };

    var trace2 = {
      // x: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      // y: [19, 14, 22, 14, 16, 19, 15, 14, 10, 12, 12, 16],
      x:{{x_axis_titles|safe}},
      y:{{y_axis_bounces}},
      type: 'bar',
      name: 'Bounces',
      marker: {
        color: '#e65c00',
        opacity: 0.5
      }
    };

    var trace3 = {
      // x: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      // y: [19, 14, 22, 14, 16, 19, 15, 14, 10, 12, 12, 16],
      x:{{x_axis_titles|safe}},
      y:{{y_axis_subscribed}},
      type: 'bar',
      name: 'Subscribed',
      marker: {
        color: '#00cc00',
        opacity: 0.5
      }
    };

    var trace4 = {
      // x: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      // y: [19, 14, 22, 14, 16, 19, 15, 14, 10, 12, 12, 16],
      x:{{x_axis_titles|safe}},
      y:{{y_axis_opened}},
      type: 'bar',
      name: 'Opened',
      marker: {
        color: '#00ffff',
        opacity: 0.5
      }
    };

    var data = [trace1, trace2, trace3, trace4];

    var layout = {
      title: 'Campaigns',
      margin: {
        b: 160,
        l: 120,
      },
      xaxis: {
        type: 'category',
        tickangle: -45,
      },
      barmode: 'group'
    };

    Plotly.newPlot('graph', data, layout);

    {% endif %}

  });

  // $('.modebar').css('display','none');

</script>
{% endblock js_block %}