cases/urls.py
from django.urls import path
from cases.views import (
    CasesListView, create_case, CaseDetailView, update_case, RemoveCaseView,
    CloseCaseView, select_contact, GetCasesView, AddCommentView,
    UpdateCommentView, DeleteCommentView, get_teams_and_users,
    AddAttachmentView, DeleteAttachmentsView)

app_name = 'cases'

urlpatterns = [
    path('', CasesListView.as_view(), name='list'),
    path('create/', create_case, name='add_case'),
    path('<int:pk>/view/', CaseDetailView.as_view(), name="view_case"),
    path('<int:pk>/edit_case/', update_case, name="edit_case"),
    path('<int:case_id>/remove/',
         RemoveCaseView.as_view(), name="remove_case"),

    path('close_case/', CloseCaseView.as_view(), name="close_case"),
    path('select_contacts/', select_contact, name="select_contacts"),
    path('get/list/', GetCasesView.as_view(), name="get_cases"),

    path('comment/add/', AddCommentView.as_view(), name="add_comment"),
    path('comment/edit/', UpdateCommentView.as_view(), name="edit_comment"),
    path('comment/remove/',
         DeleteCommentView.as_view(), name="remove_comment"),

    path('attachment/add/',
         AddAttachmentView.as_view(), name="add_attachment"),
    path('attachment/remove/', DeleteAttachmentsView.as_view(),
         name="remove_attachment"),
    path('get_teams_and_users/', get_teams_and_users,
         name="get_teams_and_users"),
]

common/urls.py
from django.contrib.auth import views as auth_views

from django.urls import path
from common.views import (
    HomeView, LoginView, ForgotPasswordView, LogoutView,
    ChangePasswordView, ProfileView,
    UsersListView, CreateUserView, UpdateUserView, UserDetailView,
    UserDeleteView, PasswordResetView,
    DocumentListView, document_create, document_update,
    DocumentDetailView, DocumentDeleteView,get_teams_and_users,
    download_document, change_user_status, download_attachment,
    add_comment, edit_comment, remove_comment,
    api_settings, add_api_settings, view_api_settings,
    update_api_settings, delete_api_settings,
    change_passsword_by_admin, google_login, create_lead_from_site,
    activate_user, resend_activation_link
)
from django.conf.urls.static import static
from django.conf import settings

app_name = 'common'


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('forgot-password/',
         ForgotPasswordView.as_view(), name='forgot_password'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change-password/',
         ChangePasswordView.as_view(), name='change_password'),
    path('profile/', ProfileView.as_view(), name='profile'),

    # User views
    path('users/list/', UsersListView.as_view(), name='users_list'),
    path('users/create/', CreateUserView.as_view(), name='create_user'),
    path('users/<int:pk>/edit/', UpdateUserView.as_view(), name="edit_user"),
    path('users/<int:pk>/view/', UserDetailView.as_view(), name='view_user'),
    path('users/<int:pk>/delete/',
         UserDeleteView.as_view(), name='remove_user'),

    path(
        'password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    # Document
    path('documents/', DocumentListView.as_view(), name='doc_list'),
    path('documents/create/', document_create, name='create_doc'),
    path('documents/<int:pk>/edit/', document_update, name="edit_doc"),
    path('documents/<int:pk>/view/',
         DocumentDetailView.as_view(), name='view_doc'),
    path('documents/<int:pk>/delete/',
         DocumentDeleteView.as_view(), name='remove_doc'),

    # download
    path('documents/<int:pk>/download/',
         download_document, name='download_document'),

    # download_attachment
    path('attachments/<int:pk>/download/',
         download_attachment, name='download_attachment'),

    path('user/status/<int:pk>/',
         change_user_status, name='change_user_status'),

    path('comment/add/', add_comment, name="add_comment"),
    path('comment/<int:pk>/edit/', edit_comment, name="edit_comment"),
    path('comment/remove/', remove_comment, name="remove_comment"),

    # settings
    path('api/settings/', api_settings, name="api_settings"),
    path('api/settings/add/', add_api_settings, name="add_api_settings"),
    path('api/settings/<int:pk>/',
         view_api_settings, name="view_api_settings"),
    path('api/settings/<int:pk>/update/',
         update_api_settings, name="update_api_settings"),
    path('api/settings/<int:pk>/delete/',
         delete_api_settings, name="delete_api_settings"),

    path('change-password-by-admin/', change_passsword_by_admin,
         name="change_passsword_by_admin"),
    path('google/login/', google_login, name="google_login"),
    path('create-lead-from-site/', create_lead_from_site,
         name='create_lead_from_site'),

    # user activate link
    path('activate-user/<uidb64>/<token>/<activation_key>/', activate_user, name='activate_user'),
    path('resend_activation_link/<userId>/', resend_activation_link, name='resend_activation_link'),
    path('get_teams_and_users/', get_teams_and_users, name="get_teams_and_users")



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from django.urls import include, path
from common.views import handler404, handler500

app_name = 'crm'

urlpatterns = [
    path('', include('common.urls', namespace="common")),
    path('', include('django.contrib.auth.urls')),
    path('marketing/', include('marketing.urls', namespace="marketing")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('leads/', include('leads.urls', namespace="leads")),
    path('contacts/', include('contacts.urls', namespace="contacts")),
    path('opportunities/',
         include('opportunity.urls', namespace="opportunities")),
    path('cases/', include('cases.urls', namespace="cases")),
    path('tasks/', include('tasks.urls', namespace="tasks")),
    path('invoices/', include('invoices.urls', namespace="invoices")),
    path('events/', include('events.urls', namespace="events")),
    path('teams/', include('teams.urls', namespace="teams")),
    path('emails/', include('emails.urls', namespace="emails")),
    # path('planner/', include('planner.urls', namespace="planner")),
    path('logout/', views.LogoutView, {'next_page': '/login/'}, name="logout"),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = handler404
handler500 = handler500

marketing/urls.py
from django.urls import path, include
from .views import (
    dashboard, contact_lists, contacts_list, contact_list_new, contact_list_detail, edit_contact,
    email_template_list, email_template_new, email_template_edit, email_template_delete,
    email_template_detail, campaign_list, campaign_new, campaign_details, campaign_delete,
    edit_contact_list, failed_contact_list_download_delete,
    campaign_link_click, campaign_open, demo_file_download, delete_contact, unsubscribe_from_campaign, contact_detail,
    download_contacts_for_campaign, create_campaign_from_template,
    download_links_clicked, delete_multiple_contacts, download_failed_contacts, delete_all_contacts,
    add_email_for_campaigns, list_all_emails_for_campaigns, edit_email_for_campaigns, delete_email_for_campaigns,
    add_blocked_domain, blocked_domain_list, edit_blocked_domain, delete_blocked_domain,
    add_blocked_email, blocked_email_list, edit_blocked_email, delete_blocked_email,
    contacts_list_elastic_search,
    # MarketingContactEmailSearch,
    # contacts_list_new
    # delete_contact_list
    # campaign_edit
    # edit_failed_contact
    # delete_failed_contact
    # failed_contact_list_detail
)

app_name = 'marketing'

urlpatterns = [
    path('', dashboard, name='dashboard'),

    path('contact-list/', contact_lists, name='contact_lists'),
    path('contacts/<int:pk>/edit/', edit_contact, name='edit_contact'),
    path('contacts/<int:pk>/delete/', delete_contact, name='delete_contact'),
    path('contacts/', contacts_list_elastic_search, name='contacts_list'),
    path('contact-list/create/', contact_list_new, name='contact_list_new'),
    # path('cl/list/cnew/', contacts_list_new, name='contacts_list_new'),
    path('contact-list/<int:pk>/detail/', contact_list_detail, name='contact_list_detail'),
    # path('contact-list/<int:pk>/failed/', failed_contact_list_detail, name='failed_contact_list_detail'),
    # path('contact-list/<int:pk>/failed/edit/', edit_failed_contact, name='edit_failed_contact'),
    # path('contact-list/<int:pk>/failed/delete/', delete_failed_contact, name='delete_failed_contact'),
    path('contact-list/<int:pk>/failed/download/',
         failed_contact_list_download_delete, name='failed_contact_list_download_delete'),
    path('contact-list/<int:pk>/edit/', edit_contact_list, name='edit_contact_list'),
    # path('cl/list/<int:pk>/delete/', delete_contact_list, name='delete_contact_list'),

    path('email-templates/', email_template_list, name='email_template_list'),
    path('email-templates/create/', email_template_new, name='email_template_new'),
    path('email-templates/<int:pk>/edit/', email_template_edit, name='email_template_edit'),
    path('email-templates/<int:pk>/detail/', email_template_detail, name='email_template_detail'),
    path('email-templates/<int:pk>/delete/', email_template_delete, name='email_template_delete'),

    path('campaigns/', campaign_list, name='campaign_list'),
    path('campaigns/create/', campaign_new, name='campaign_new'),
    # path('cm/<int:pk>/edit/', campaign_edit, name='campaign_edit'),
    path('campaigns/<int:pk>/details/', campaign_details, name='campaign_details'),
    path('campaigns/<int:pk>/delete/', campaign_delete, name='campaign_delete'),
    path('cm/link/<int:link_id>/e/<int:email_id>/', campaign_link_click, name='campaign_link_click'),
    path('cm/track-email/<int:campaign_log_id>/contact/<int:email_id>/', campaign_open, name='campaign_open'),
    path('demo-file-download-for-contacts-list/', demo_file_download, name='demo_file_download'),
    path('unsubscribe-from-campaign/<int:contact_id>/<int:campaign_id>/', unsubscribe_from_campaign, name="unsubscribe_from_campaign"),
    path('contacts/<int:contact_id>/view/', contact_detail, name="contact_detail"),
    path('download-contacts-for-campaign/<int:compaign_id>/', download_contacts_for_campaign, name="download_contacts_for_campaign"),
    path('create-campaign-from-template/<int:template_id>/', create_campaign_from_template, name="create_campaign_from_template"),
    path('download-links-clicked/<int:campaign_id>/', download_links_clicked, name="download_links_clicked"),
    path('delete_multiple_contacts/', delete_multiple_contacts, name="delete_multiple_contacts"),
    path('download-failed-contacts/<int:contact_list_id>/', download_failed_contacts, name="download_failed_contacts"),
    path('delete_all_contacts/<int:contact_list_id>/', delete_all_contacts, name="delete_all_contacts"),
    path('add-email-for-campaigns/', add_email_for_campaigns, name="add_email_for_campaigns"),
    path('list-all-emails-for-campaigns/', list_all_emails_for_campaigns, name="list_all_emails_for_campaigns"),
    path('edit-email-for-campaigns/<int:pk>/', edit_email_for_campaigns, name="edit_email_for_campaigns"),
    path('delete-email-for-campaigns/<int:pk>/', delete_email_for_campaigns, name="delete_email_for_campaigns"),

    path('add-blocked-domain/', add_blocked_domain, name="add_blocked_domain"),
    path('blocked-domain-list/', blocked_domain_list, name="blocked_domain_list"),
    path('edit-blocked-domain/<int:blocked_domain_id>/', edit_blocked_domain, name="edit_blocked_domain"),
    path('delete-blocked-domain/<int:blocked_domain_id>/', delete_blocked_domain, name="delete_blocked_domain"),

    path('add-blocked-email/', add_blocked_email, name="add_blocked_email"),
    path('blocked-email-list/', blocked_email_list, name="blocked_email_list"),
    path('edit-blocked-email/<int:blocked_email_id>/', edit_blocked_email, name="edit_blocked_email"),
    path('delete-blocked-email/<int:blocked_email_id>/', delete_blocked_email, name="delete_blocked_email"),

    # path('search-marketing-contact-emails/', include('haystack.urls')),
    # path('elastic-search/', contacts_list_elastic_search),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load compress %}
{% load thumbnail %}
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Shot in the Dark</title>
    <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" />

    {% compress css %}
    <link href="{% static 'css/main.scss' %}" type="text/x-scss" rel="stylesheet">
    <link href="{% static 'css/mention.scss' %}" type="text/x-scss" rel="stylesheet">
    {% endcompress %}
    {% block extralinks %} {% endblock %}
  </head>
  <body class="main_body_bg_color">
    <div class="wrapper">
      
      <header>
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top">

          <a class="navbar-brand" href="{% url 'common:home' %}">Shot in the Dark</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
          </button>
          {% if request.user.is_authenticated %}
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item"><a class="nav-link" id="dashboard" href="{% url 'common:home' %}">Dashboard</a></li>
              {% if request.user.role == "ADMIN"  or request.user.is_superuser %}
              <li class="nav-item"><a class="nav-link" id="users" href="{% url 'common:users_list' %}">Users</a></li>
              {% endif %}
              <li class="nav-item"><a class="nav-link" id="accounts" href="{% url 'accounts:list' %}">Accounts</a></li>
              <li class="nav-item"><a class="nav-link" id="contacts" href="{% url 'contacts:list' %}">Contacts</a></li>
              <li class="nav-item"><a class="nav-link" id="leads" href="{% url 'leads:list' %}">Leads</a></li>
              <li class="nav-item"><a class="nav-link" id="opportunities"href="{% url 'opportunities:list' %}">Opportunities</a></li>
              <li class="nav-item"><a class="nav-link" id="cases" href="{% url 'cases:list' %}">Cases</a></li>
              <li class="nav-item"><a class="nav-link" id="documents" href="{% url 'common:doc_list' %}">Documents</a></li>
              {% if request.user.role == "ADMIN" or request.user.is_superuser %}
              <li class="nav-item"><a class="nav-link" id="users" href="{% url 'common:api_settings' %}">Settings</a></li>
              {% endif %}
            </ul>
            <ul class="navbar-nav navbar-right my-2 my-lg-0">
              <li class="nav-item dropdown">
                <a href="#" class="dropdown-toggle abcd nav-link" data-toggle="dropdown" role="button" aria-haspopup="true"
                  aria-expanded="false" >
                {% if not request.user.profile_pic %}
                <img src="{% static 'images/user.png' %}" alt="Micro profile pic">
                {% else %}
                {% thumbnail request.user.profile_pic "25x25" as im %}
                <img src="{{ im.url }}">
                {% endthumbnail %}
                {% endif %}
                <b class="caret"></b></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  {% if request.user.email != "admin@micropyramid.com" %}
                  <a class="dropdown-item" href="/change-password/"><i class="fas fa-key"></i> Change Password</a>
                  {% endif %}
                  <a class="dropdown-item" href="{% url 'common:profile' %}"><i class="fas fa-user"></i> Profile</a>
                  <a class="dropdown-item" href="{% url 'common:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
                </div>
              </li>
            </ul>
          </div>
          {% endif %}
        </nav>
      </header>
      
      
      <div id="mainbody" class="main_container" style="padding-top:65px;">
        
        {% block breadcrumb %}
        {% endblock %}
        
        {% block content %}
        {% endblock %}
      </div>
      
    </div>

    {% block js_block %}
    <script src="{% static 'js/index.js' %}"></script>
    {% endblock js_block %}
    <script type="text/javascript">
      $(document).ready(function(){
          word = window.location.pathname.split('/')[1]
          if(word == ""){
            $("#dashboard").addClass('active')
          }
          else{
            $('#' + word).addClass('active')
          }
      });
    </script>
  </body>
</html>

templates/change_password.html
{% extends 'sales/base.html' %}
{% load staticfiles %}

{% block content %}
<form id="add_form" method="POST" action="" novalidate>
  <div class="overview_form_block row marl justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
         <div class="card-title">
          Change Password
        </div>
          <div class="row marl no-gutters">
            <div class="col-md-12">
              
              {% if not user_obj %}
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="exampleInputEmail1">New Password {% if change_password_form.Newpassword.field.required %}<span class="error">*</span>{% endif %}</label>
                  <input type="password" class="form-control" name="Newpassword" value="{{ request.POST.Newpassword }}" placeholder="New Password">
                </div>
                <span class="error">{{ errors.Newpassword }}</span>
              </div>
              {% endif %}
              <div class="filter_col col-md-12">
                <ul style="margin-left:0; padding-left:0;">
                  <li style="font-size: 0.9em; list-style: none;">Your password can't be too similar to your other personal information.</li>
                  <li style="font-size: 0.9em; list-style: none;">Your password must contain at least 8 characters.</li>
                  <li style="font-size: 0.9em; list-style: none;">Your password can't be a commonly used password.</li>
                  <li style="font-size: 0.9em; list-style: none;">Your password can't be entirely numeric.</li>
                </ul>
              </div>
              {% if not user_obj %}
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="exampleInputEmail1">Confirm New Password {% if change_password_form.confirm.field.required %}<span class="error">*</span>{% endif %}</label>
                  <input type="password" class="form-control" name="confirm" value="{{ request.POST.confirm }}" placeholder="Confirm Password">
                </div>
                <span class="error">{{ errors.confirm }}</span>
              </div>
              {% endif %}
            </div>
          </div>
          <br>
          <div class="row marl buttons_row form_btn_row text-center">
            <button class="btn btn-default save" type="submit">Change Password</button>
            <button type="button" class="btn btn-default" onclick='window.open($(this).attr("href"),target = "_self")' href="{% url 'common:profile'%}" style="background:#099CBE;color:white">Cancel</button>
            
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock content %}

templates/contact_list_digg_paginator.html
{% spaceless %}
{% ifnotequal pages 1 %}


{% ifnotequal bounced_contacts_page 1  %}
<li><a href="{% if get_params %}?{{ get_params }}&{% else %}?{% endif %}bounced_contacts_page=1"
        rel="page">{{"<<"|safe}}</a></li>
{% endifnotequal %}
{% if has_previous %}
<li><a href="{% if get_params %}?{{ get_params }}&{% else %}?{% endif %}bounced_contacts_page={{ previous }}"
        rel="page">{{"<"|safe}}</a></li>
{% endif %}
{% if not in_leading_range %}
{% for p in pages_outside_trailing_range %}
<li><a href="{% if get_params %}?{{ get_params }}&{% else %}?{% endif %}bounced_contacts_page={{ p }}"
        rel="page">{{ p }}</a></li>
{% endfor %}

{% endif %}
{% for p in page_range %}
{% if p == bounced_contacts_page %}
<li><span class="active">{{ p }}</span></li>
{% else %}
<li><a href="{% if get_params %}?{{ get_params }}&{% else %}?{% endif %}bounced_contacts_page={{ p }}"
        rel="page">{{ p }}</a></li>
{% endif %}
{% endfor %}
{% if not in_trailing_range %}

{% for p in pages_outside_leading_range reversed %}
<li><a href="{% if get_params %}?{{ get_params }}&{% else %}?{% endif %}bounced_contacts_page={{ p }}"
        rel="page">{{ p }}</a></li>
{% endfor %}
{% endif %}
{% if has_next %}
<li><a href="{% if get_params %}?{{ get_params }}&{% else %}?{% endif %}bounced_contacts_page={{ next }}"
        rel="page">{{">"|safe}}</a></li>
{% endif %}
{% ifnotequal bounced_contacts_page pages  %}
<li><a href="{% if get_params %}?{{ get_params }}&{% else %}?{% endif %}bounced_contacts_page={{ pages }}"
        rel="page">{{">>"|safe}}</a></li>
{% endifnotequal %}

{% endifnotequal %}
{% endspaceless %}

templates/forgot_password.html
{% load staticfiles %}
{% load compress %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Shot in the Dark</title>
    
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.0/css/bootstrap.min.css" />
    <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" />
    
    {% compress css %}
    <link href="{% static 'css/main.scss' %}" type="text/x-scss" rel="stylesheet">
    {% endcompress %}
    {% block extralinks %}{% endblock %}
  </head>
  <body class="login_register_body">
    <div class="container">
      <div class="row marl justify-content-center login_row">
        <div class="col-md-6 col-lg-6 col-xl-4">
          <div class="login_block">
            <div class="login_form_block">
              <div class="welcome">Forgot Password?</div>
              <form method="POST" action="">
                <div class="form-group">
                  <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Email" name="email">
                </div>
                <div class="forgot">Back to login <a href="{% url "common:login" %}">Click Here?</a></div>
                <button type="submit" class="btn btn-danger">Reset Password</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

templates/login.html
{% load staticfiles %}
{% load compress %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Shot in the Dark</title>
  
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.0/css/bootstrap.min.css" />
  <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js"></script>
  <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" />
  
  {% compress css %}
  <link href="{% static 'css/main.scss' %}" type="text/x-scss" rel="stylesheet">
  {% endcompress %}
  {% block extralinks %}{% endblock %}
</head>

<body class="login_register_body">
  {% if messages %}
  <ul style="font-size: 1.5em;" class="text-center mt-5">
    {% for message in messages %}
    {{ message|safe }}
    {% endfor %}
  </ul>
  {% endif %}
  <div class="container">
    <div class="row marl justify-content-center login_row">
      <div class="col-md-6 col-lg-6 col-xl-4">
        <div class="login_block">
          <div class="login_form_block">
            <div class="welcome">Shot in the Dark CRM</div>
            <form method="POST" action="">
              <div class="form-group">
                <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Email" name="email">
                <span class="error">{{form.email.errors}}</span>
              </div>
              <div class="form-group">
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password"
                  name="password">
                <span class="error">{{form.password.errors}}</span>
              </div>
              <div class="forgot">Forgot Password <a href="{% url "common:password_reset" %}">Click Here?</a></div>
              {% if error %}
              <p class="error">{{ message }}</p>
              {% endif %}
              <button type="submit" class="btn btn-danger">Login</button>
              &nbsp;
              {% if ENABLE_GOOGLE_LOGIN and GP_CLIENT_SECRET and GP_CLIENT_ID %}
              <a href="{% url 'common:google_login' %}" class="btn btn-primary">Google Login</a>
              {% endif %}
            </form>

          </div>
        </div>
      </div>
    </div>
  </div>
</body>

</html>

templates/new_user.html
hello {{user.email}},

<p>Your account has been successfully created in the Shot in the Dark CRM by {{created_by.email}}</p>

templates/registration.html
{% extends 'sales/base.html' %}
{% block content %}
<h1>Registration</h1>
<form method="POST" class="user-form">
  {{ reg_form.as_p }}
  <button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}